user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main buffer=32k flush=1m;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;

    server {
        listen 80;
        listen [::]:80;
        server_name _;

        root /data/nginx/html/tag-image;

        location = /health {
            access_log off;
            default_type text/plain;
            return 200 "healthy\n";
        }

        client_max_body_size 100m;

        location / {
            try_files $uri $uri/ =404;
            add_header Cache-Control "public, max-age=31104000, s-maxage=864000" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }
    }
}
